### ISSUE TITLE
"message" class and instance method being defined

### ISSUE THREAD

**Issue by coatezy** [jgarber623/svgeez#26]
A class and instance method of message is defined with the gem installed.

``` bash 
BasicObject.message => #<IO:<STDOUT>>
```

I first noticed when trying to access `#message` on a model. After running git bisect I discovered the commit that introduced this added svgeez to the project.

If I remove the gem from the project, message is no longer defined. If I start a new Rails project and include svgeez the method is define.

Tested with version 1.0.1.

I'm guessing it is a dependency of svgeez that is introducing this?

**Comment by jgarber623** [comment]
@coatezy Thanks for filing this issue. I'm having a bit of trouble wrapping my head around the problem you're describing. Can you provide a link to a project demonstrating this misbehavior or write up some steps to reproduce? Thanks!

**Comment by Uepsilon** [comment]
We've stumbled across this too. Here's some example code.

```ruby
2.7.2 :001 > require 'ostruct'
 => true
2.7.2 :002 > class Foo < OpenStruct; end
 => nil
2.7.2 :003 > x = Foo.new(message: :bar)
 => #<Foo message=:bar>
2.7.2 :004 > x.message
 => :bar
2.7.2 :005 >
2.7.2 :006 >
2.7.2 :007 > require 'svgeez'
 => true
2.7.2 :008 > class Foo < OpenStruct; end
 => nil
2.7.2 :009 > x = Foo.new(message: :bar)
 => #<Foo message=:bar>
2.7.2 :010 > x.message
 => #<IO:<STDOUT>>
```

it's due to the gem requiring 'mkmf'
https://github.com/jgarber623/svgeez/blob/main/lib/svgeez.rb#L3

our solution for now is to not require the gem in the gemfile but only where needed, in our case a raketask. 

`gem 'svgeez', require: false`
