### ISSUE TITLE
method to configure svgo?

### ISSUE THREAD

**Issue by stephenchai** [jgarber623/svgeez#27]
Is there a way to specify either a custom `.svgo.yml` or use inline JSON to configure how I'd like svgo to behave?

In effect, I'd like to use something along the lines of `svgeez -s ./img/input -d ./img/output --with-svgo --config=./.svgo-custom.yml`

**Comment by jgarber623** [comment]
@stephenchai Thanks for the question!

At present, there's no way to configure SVGO through svgeez. There _is_ an open PR (#21) that's somewhat related, but more limited in scope.

What kind of SVGO configuration would you want to do in a YML file?

**Comment by pmackay** [comment]
I'd also find custom configuration of SVGO very useful. An example would be to define a custom config to enable specific plugins.

**Comment by renatodeleao** [comment]
Shameless bump: Config for SVGO, via `config file` or CLI flags 👍  

(works like charm aside from that)
