### ISSUE TITLE
SVG doesn't render correctly

### ISSUE THREAD

**Issue by dmakhmutov** [jgarber623/svgeez#75]
Hello
I faced issues sometimes SVG doesn't render correctly.

-   Bug output: https://jsfiddle.net/DamirMax/qta57yfw/1/
-   Fix [#32](https://github.com/jgarber623/svgeez/pull/32) that helped https://jsfiddle.net/DamirMax/raxu4p2s/1/

Seems like `position:absolute; width: 0; height: 0;` also better in cases when we use `defs`. Any tips on how to modify SVG without modifying the library code are welcome. Thanks

**Comment by jgarber623** [comment]
@dmakhmutov First off, I'm so incredibly sorry for not addressing (or even acknowledging) this issue and _thank you_ for the helpful example links to JSFiddle.

I was able to achieve a better outcome (starting with [the initial JSFiddle](https://jsfiddle.net/DamirMax/qta57yfw/1/)) by replacing `style="display: none;"` with `visbility="hidden"` ([MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/visibility)). This change resulted in the icon displaying correctly, but with a black/default fill:

<img width="185" alt="image" src="https://github.com/jgarber623/svgeez/assets/73866/dd7dbfea-247c-459b-94f2-9d17ced467fa">

I addressed _that_ by adding some CSS in a `<style>` element (in either the `<head>` or `<body>`, doesn't matter for this demonstration):

```css
svg use { fill: #9061af; }
```

<img width="181" alt="image" src="https://github.com/jgarber623/svgeez/assets/73866/c4f6f7d1-bcc3-45d8-9700-55ec975e612d">

I'll experiment a bit more with the `visibility` attribute and see if that's a suitable replacement for the inline `style` attribute on the generated `<svg>`. If it is, I'll slate the change for a v5.0.0 release.
